# Generated by Django 2.0.3 on 2018-06-12 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('our_journey', models.TextField()),
                ('our_history_and_passions', models.TextField(blank=True, null=True)),
                ('about_image', models.ImageField(upload_to='About us')),
            ],
        ),
        migrations.CreateModel(
            name='Basic_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slogan', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='About us')),
                ('phone_1', models.CharField(max_length=15)),
                ('phone_2', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('office_address', models.TextField()),
                ('promo_video', models.URLField(blank=True, null=True)),
                ('google_map_link', models.URLField(blank=True, null=True)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('google_plus_link', models.URLField(blank=True, null=True)),
                ('youtube_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=150)),
                ('course_url', models.CharField(max_length=150)),
                ('thumbnail_image', models.ImageField(upload_to='Courses')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('category_url', models.CharField(max_length=50)),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to='Course_Category')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.CharField(max_length=3)),
                ('month', models.CharField(max_length=10)),
                ('start_and_end_time', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='Events')),
                ('gallery_image1', models.FileField(blank=True, null=True, upload_to='Gallery/events')),
                ('gallery_image2', models.FileField(blank=True, null=True, upload_to='Gallery/events')),
                ('gallery_image3', models.FileField(blank=True, null=True, upload_to='Gallery/events')),
                ('gallery_image4', models.FileField(blank=True, null=True, upload_to='Gallery/events')),
                ('gallery_image5', models.FileField(blank=True, null=True, upload_to='Gallery/events')),
                ('gallery_image6', models.FileField(blank=True, null=True, upload_to='Gallery/events')),
                ('gallery_image7', models.FileField(blank=True, null=True, upload_to='Gallery/events')),
                ('gallery_image8', models.FileField(blank=True, null=True, upload_to='Gallery/events')),
                ('gallery_image9', models.FileField(blank=True, null=True, upload_to='Gallery/events')),
                ('gallery_image10', models.FileField(blank=True, null=True, upload_to='Gallery/events')),
                ('gallery_image11', models.FileField(blank=True, null=True, upload_to='Gallery/events')),
                ('gallery_image12', models.FileField(blank=True, null=True, upload_to='Gallery/events')),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
                ('date_and_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='Profile_picture/')),
                ('father_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('institute', models.CharField(blank=True, max_length=255, null=True)),
                ('facebook', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter', models.CharField(blank=True, max_length=255, null=True)),
                ('youtube', models.CharField(blank=True, max_length=255, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('Image', models.ImageField(upload_to='Projects')),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=400, verbose_name='Question')),
                ('question_file', models.FileField(blank=True, null=True, upload_to='Question-file', verbose_name='Question')),
                ('option1', models.CharField(blank=True, max_length=50, null=True)),
                ('option2', models.CharField(blank=True, max_length=50, null=True)),
                ('option3', models.CharField(blank=True, max_length=50, null=True)),
                ('option4', models.CharField(blank=True, max_length=50, null=True)),
                ('correct_answer', models.CharField(blank=True, max_length=25, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Course')),
            ],
        ),
        migrations.CreateModel(
            name='SingleVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=150)),
                ('video_url', models.CharField(max_length=150)),
                ('video_link', models.URLField()),
                ('is_public', models.BooleanField(default=False)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_text', models.CharField(blank=True, max_length=100, null=True)),
                ('big_text', models.CharField(max_length=100)),
                ('paragraph', models.CharField(max_length=250)),
                ('slide_image', models.ImageField(upload_to='Slider_Image')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_file', models.FileField(blank=True, null=True, upload_to='Student-answer')),
                ('answer_text', models.CharField(blank=True, max_length=255, null=True)),
                ('counter', models.PositiveIntegerField(blank=True, null=True)),
                ('is_pass', models.BooleanField(default=False)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Course')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Question')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subcribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcriber_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TakenCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken_course_title', models.CharField(max_length=255, null=True)),
                ('taken_course_url', models.CharField(max_length=255, null=True)),
                ('taken_course_image', models.ImageField(null=True, upload_to='User/TakenCourses')),
                ('taken_course_category', models.CharField(max_length=255, null=True)),
                ('taken_category_url', models.CharField(max_length=255, null=True)),
                ('view', models.PositiveIntegerField(blank=True, null=True)),
                ('taken_time', models.DateTimeField(auto_now=True)),
                ('last_visited', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taken_courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TakenQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taken_quizzes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=100)),
                ('person_designation', models.CharField(max_length=100)),
                ('person_comment', models.TextField()),
                ('person_image', models.ImageField(upload_to='Testimonial')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WatchVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view', models.IntegerField(blank=True, default=0, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.CourseCategory')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_video', to='web.TakenCourse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vedio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.SingleVideo')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='course_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.CourseCategory'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.CourseLevel'),
        ),
        migrations.AlterUniqueTogether(
            name='takencourse',
            unique_together={('user', 'taken_course_url')},
        ),
    ]
