from django.urls import path, re_path
from django.conf.urls import url
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('course/<category>', views.courseCategory, name='single_category'),
    path('course/<category>/<level>', views.drawing_course, name='drawing_course'),
    path('<category>/course/<course>', views.course, name='single_course'),
    path('all-courses', views.all_course, name='all_course'),
    path('popular-courses', views.popular_course, name='popular_course'),
    path('resent-courses', views.recent_course, name='recent_course'),
    path('event/<event_id>', views.event, name='single_event_page'),
    path('contact', views.contact, name='contact_page'),
    path('about-us', views.about_us, name='about_page'),
    path('faq', views.faq, name='faq_page'),
    path('login', views.get_login, name='get_login'),
    path('logout', views.get_logout, name='logout'),
    path('profile/<username>/', views.get_user_profile, name='user_profile'),
    path('sign-up', views.signup, name='sign-up'),
    path('user-message', views.user_message, name='user_message'),
    # path('activate/<uidb64>/<token>', views.activate, name='activate'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
     views.activate, name='activate'),
    # path('profile/<slug:slug>/', views.ProfilePage.as_view(), name='user_profile'),
    path('update_profile/', views.update_profile, name='update_profile'),
    path('events_list', views.EventListView.as_view(), name='event_list'),
    path('subcriber', views.subscriber, name='subcriber'),
    path('search', views.search, name='search'),
    path('<user>/my-course/', views.my_course, name='my_course'),
    # path('<user>/my-course/', views.TakenCourseList.as_view(), name='my_course')
    path('<user>/delete_course/<int:pk>/', views.taken_course_delete, name='delete_course'),
    # path('taken-quiz/<int:pk>/', views.take_quiz, name='take-quiz'),
    path('<course>/question-list/', views.question_list, name='question-list'),
    path('question/', views.take_quiz, name='question'),
    path('student-answer/<username>/', views.student_answer, name='student-answer'),
    path('mcq/<int:question_id>/', views.score, name='vote'),
    path('all-answer/', views.AllAnswer.as_view(), name="all-answer"),
    path('quize-datails/', views.quize_details, name='quize-details'),
    path('vedio_link/', views.vedio_link, name='vedio_link'),
    path('<category>/<course>/<video>/', views.single_video, name='single_vedio'),
    path('<course_watch>/watch_vedio/', views.watch_vedio, name='watch_vedio'),
    # path('api/status/', views.api_status, name='api-status'),
]
